### ISSUE TITLE
Starting a bluetooth connection

### ISSUE THREAD

**Issue by premasagar** [hybridgroup/cylon-wiced-sense#3]
I have just aquired a Wiced Sense device and I can successfully connect to it with the official iOS app. I have tried using the example code for connecting with cylon.js but I can't get a connection established.

I am using a Mac and have Bluetooth enabled. The device is on and its power light is active. The device does appear in the list of available devices when I open Mac's Bluetooth Preferences. Should the device be connected in that list, before I start the cylon.js code? Is the uuid of `'207377654321'` in the example code exactly what I should be using, or do I need to adjust it for my device - or is it just an arbitrary unique id to use within my cylon-based code?

The Wiced Sense [info page](http://www.broadcom.com/products/wiced/sense/) ([alt](http://www.broadcom.com/wicedsense)) and [community pages](http://community.broadcom.com/community/wiced-smart) on Broadcom's website seems to have disappeared.

Additionally, I am unsure what the USB cable for the device achieves. It seems to disable bluetooth on the device. Can I use the cable to get data from the device with cylon, without using Bluetooth?

I'd be very grateful for any suggestions you can make.

**Comment by deadprogram** [comment]
Hi @premasagar 

You need to obtain the OSX id for the WICED Sense, which will be different for every device on every OSX system. The easiest way is to run the `blescan.js` program that is part of `cylon-ble`.

The USB port on the WICED Sense can only be used to flash new firmware on it, for people who are using the WICED SDK, at least as far as I know.

Hope that helps!

**Comment by premasagar** [comment]
Thanks a lot, @deadprogram. I'll try that out.

**Comment by premasagar** [comment]
It worked! Cheers.
